### ISSUE TITLE
Проблемы, обнаруженные в программе

### ISSUE THREAD

**Issue by NikitaSpirin321234** [thehighestmath/SummerPractice#12]
https://github.com/thehighestmath/SummerPractice/commit/454ff7c25f7e46d26c8fc823cff578fe94f2ca7c

Возникает проблема создания новой вершины в ситуации, когда количество удаленных вершин + количество в графе равно 26. 
Допустим при добавлении 26 вершин в граф и при последующем удалении хотя бы одной вершины, добавить новые вершины не предоставляется возможным.

**Comment by Akibardin** [comment]
>Возникает проблема создания новой вершины в ситуации, когда количество удаленных вершин + количество в графе равно 26.
Допустим при добавлении 26 вершин в граф и при последующем удалении хотя бы одной вершины, добавить новые вершины не предоставляется возможным.


Исправлено в https://github.com/thehighestmath/SummerPractice/commit/3ae806a9ef6e1f6c564a159e6550d816d21dff53

**Comment by NikitaSpirin321234** [comment]
При перетягивании существующих вершин возникает проблема их выведения за границы поля:

![image](https://user-images.githubusercontent.com/43099701/86477791-db737900-bd51-11ea-9da7-718ddbec59f2.png)

**Comment by NikitaSpirin321234** [comment]
При близком расположении вершин, веса рёбер между ними не видны:

![image](https://user-images.githubusercontent.com/43099701/86479033-0a8aea00-bd54-11ea-9b39-88744f93fe26.png)

**Comment by Akibardin** [comment]
`При близком расположении вершин, веса рёбер между ними не видны:`

[Пример](http://graphonline.ru/?graph=yympPKYwtwKLmGIZ)
Здесь так же при близком расположении вершин не виден вес ребра

**Comment by thehighestmath** [comment]
> `При близком расположении вершин, веса рёбер между ними не видны:`
> 
> [Пример](http://graphonline.ru/?graph=yympPKYwtwKLmGIZ)
> Здесь так же при близком расположении вершин не виден вес ребра

А у нас будет видно)

**Comment by NikitaSpirin321234** [comment]
Странный текст сообщения при добавлении ребра между вершинами, между которыми уже существует ребро:

![image](https://user-images.githubusercontent.com/43099701/86479746-6dc94c00-bd55-11ea-9b9f-1796eb6e183b.png)

**Comment by NikitaSpirin321234** [comment]
При создании, допустим, трёх вершин a, b и c, и расположении их на одной прямой, вес ребра ab не виден из-за вершины c, находящейся между вершинами a и b:

![image](https://user-images.githubusercontent.com/43099701/86481708-33fa4480-bd59-11ea-8540-3f8c1c398e21.png)

**Comment by thehighestmath** [comment]
Исправлено в https://github.com/thehighestmath/SummerPractice/commit/6a666e071448622cfb971805dd485f51814e1e59

**Comment by NikitaSpirin321234** [comment]
В случае, когда у вершины уже имеется хотя бы один сосед, и пользователь из этой вершины проводит ребро в место, где нет вершины:

![image](https://user-images.githubusercontent.com/43099701/86913996-32999500-c128-11ea-9fd2-3a93b828821e.png)

иногда выводится некорректное сообщение:

![image](https://user-images.githubusercontent.com/43099701/86914017-41804780-c128-11ea-82d5-94dc1ed9a454.png)

**Comment by NikitaSpirin321234** [comment]
При введении слишком большого значения веса ребра:

![image](https://user-images.githubusercontent.com/43099701/86950537-ec105e80-c158-11ea-85f9-1fb57ac39d48.png)

это ребро не инициализируется:

![image](https://user-images.githubusercontent.com/43099701/86950593-01858880-c159-11ea-9b1d-2e8fa69e33ee.png)

**Comment by NikitaSpirin321234** [comment]
При создании графа, а затем после поэтапного удаления вершин с помощью radioButton "Удалить вершину" до полного удаления графа, становится невозможно добавить новую вершину.

**Comment by Akibardin** [comment]
>При введении слишком большого значения веса ребра:
это ребро не инициализируется

>При создании графа, а затем после поэтапного удаления вершин с помощью radioButton "Удалить вершину" до полного удаления графа, становится невозможно добавить новую вершину.

> В случае, когда у вершины уже имеется хотя бы один сосед, и пользователь из этой вершины проводит ребро в место, где нет вершины:
иногда выводится некорректное сообщение:

Исправлено в https://github.com/thehighestmath/SummerPractice/pull/19/commits/7eb7db9fa3e930e329e542f14af2b770b0d78723
