### ISSUE TITLE
Тестовый GUI

### ISSUE THREAD

**Issue by thehighestmath** [thehighestmath/SummerPractice#3]
**Создана новая ветка**
https://github.com/thehighestmath/SummerPractice/tree/testGUI

Можно визуально вводить граф, но только при выборе radiobutton'a "Ввод вершин"
MainWindow.java
MyJComponent.java
![H-rDYfyivMc](https://user-images.githubusercontent.com/42893255/85770595-c0868080-b723-11ea-815e-e4a1c830c77d.jpg)

**Comment by thehighestmath** [comment]
Нужно сделать вывод веса, получившегося дерева
Сделать стягивание более красивым
  * не делать двойное ребро 
    - т.е. скорее всего удалять ребро из обычного дерева 
    - или эти ребра на одной прямой располагать
      + чтобы одно другим затиралось


![Por_B63LpUI](https://user-images.githubusercontent.com/42893255/85861925-b74fef00-b7c9-11ea-926c-fcc96457d591.jpg)

**Comment by thehighestmath** [comment]
Введен граф

![Снимок экрана от 2020-06-26 18-31-13](https://user-images.githubusercontent.com/42893255/85874570-824c9800-b7db-11ea-9d2a-788ed45ef125.png)

Результат работы алгоритма
![Снимок экрана от 2020-06-26 18-31-22](https://user-images.githubusercontent.com/42893255/85874538-752fa900-b7db-11ea-972e-7496985edce8.png)
 
***
Добавлено 2 новых ребра и 1 новая вершина
![Снимок экрана от 2020-06-26 18-31-53](https://user-images.githubusercontent.com/42893255/85874540-75c83f80-b7db-11ea-83a8-13646f0c1247.png)

Результат
![Снимок экрана от 2020-06-26 18-32-06](https://user-images.githubusercontent.com/42893255/85874541-7660d600-b7db-11ea-9854-962ab2b710c0.png)

**Comment by thehighestmath** [comment]
https://github.com/thehighestmath/SummerPractice/commit/0850888be3feb219b7e33a59b04eef71062c583f

Чтобы запустить программу у себя нужно
  * скачать JVM
  * скачать файл https://github.com/thehighestmath/SummerPractice/blob/0850888be3feb219b7e33a59b04eef71062c583f/build/libs/SummerPractice-all-1.0-SNAPSHOT.jar

**Comment by Akibardin** [comment]
Не актуально в связи с значительными изменениями в [ветке расширения граф. функционала](https://github.com/thehighestmath/SummerPractice/tree/fixVisualization)
