### ISSUE TITLE
То, что нуждается во внимании

### ISSUE THREAD

**Issue by thehighestmath** [thehighestmath/SummerPractice#4]
## Петли на вершинах
  * они не отображаются
  * они есть
-- Это плохо

## Введено НЕ число в весе ребра
  * ребро есть, а веса нет --> непорядок
  * но программа не падает
  * из-за этого **вес следующего** ребра занимает **вес предыдущего** ребра!

**Comment by thehighestmath** [comment]
## Двойные вершины
  + Двойной клик порождает 2 вершины, это плохо

**Comment by Akibardin** [comment]
https://github.com/thehighestmath/SummerPractice/tree/ExtendGUI 
В данной ветке будет расширяться интерфейс. На данный момент имеется следующее:

- Добавлено перемещение введенных пользователем вершин

- Пофикшен баг с двойным кликом

Интерфейс кнопок будет отредактирован позже. Имена методов, если таковые так же не несут ясности, будут изменены

**Comment by Akibardin** [comment]
Пофикшен баг с появлением петель

UPD: теперь точно

**Comment by Akibardin** [comment]
_Введено НЕ число в весе ребра
ребро есть, а веса нет --> непорядок
но программа не падает
из-за этого вес следующего ребра занимает вес предыдущего ребра!_

Данная подзадача перемещена [сюда](https://github.com/thehighestmath/SummerPractice/issues/6).
