### ISSUE TITLE
Расширение функционала графики и интерфейса

### ISSUE THREAD

**Issue by Akibardin** [thehighestmath/SummerPractice#6]
Задачи на текущий момент:

- [x] Реализация пошаговой визуализации(и декомпозиция этой задачи).
- В связи с тем, что при появлении шаговой визуализации, пользователь сможет добавлять ребра и вершины, два  решения.
 <s> - [ ] 1) Запрет на изменение составляющих графа, пока не алгоритм не завершит работу.</s>
  - [x] 2) При изменении составляющих графа откатывать алгоритм на первый шаг.
На данном моменте, первая итерация закончена. 
- [x] Фикс бага - Вместо веса ребра вводится какой-либо мусор, веса нет, при вводе следующего ребра новый вес записывается в пред. ребро. Так же фикс аналогичного бага возникающего при закрытии диалогового окна.
- [x] Добавление удаления ребер и вершин (и соответственно всех инцидентных ребер)
- [x] Добавление окна, выводящего сообщение о текущем шаге(Логи).
- [x] Добавление раскраски ребер в пошаговом режиме(новое ребро - зеленое, цикл - красное, остовное дерево{промежуточное и конечное} - синее] )
- [x] Вывод веса оставного дерева

**Comment by thehighestmath** [comment]
> Фикс бага - Вместо веса ребра вводится какой-либо мусор, веса нет, при вводе следующего ребра новый вес записывается в пред. ребро. Так же фикс аналогичного бага возникающего при закрытии диалогового окна.

Исправлено в 6c93a127985501e0852c1f4f2c13a188e4bef43e

**Comment by thehighestmath** [comment]
> Реализация пошаговой визуализации

Исправление ошибки индексации cb04bbfc3aa84683f2d67160d788eaf13b2f81aa
Шаговая визуализация 32f73ed905a6e62eaeadf6ddbdc952d8193ac22e

**Comment by Akibardin** [comment]
>  2) При изменении составляющих графа откатывать алгоритм на первый шаг.


Добавлено в https://github.com/thehighestmath/SummerPractice/commit/b15063af718121fd0daf36b5e44a06b08883a6f5

**Comment by thehighestmath** [comment]
>  Добавление окна, выводящего сообщение о текущем шаге(Логи).

Добавлено в a8aa35d60d253f468e26939bac638a1e10fd1003

**Comment by thehighestmath** [comment]
> Вывод веса оставного дерева

Добавлено в 57348ab4bf3405d0791313c32ae90e7f9143ede2

**Comment by Akibardin** [comment]
> Добавление удаления ребер и вершин (и соответственно всех инцидентных ребер)

Добавлено в 3ba1a957340a45cb8901aa5ae8f89b087c5ba906

**Comment by Akibardin** [comment]
> Добавление раскраски ребер в пошаговом режиме(новое ребро - зеленое, цикл - красное, остовное дерево{промежуточное и конечное} - синее] )

 Добавлено в 39bc43d4beb4bf4398c64c1faa4fa30a966ed24b
